### ISSUE TITLE
Regielokaal vrij maken

### ISSUE THREAD

**Issue by MaxTechnics** [luchtdoos/Musical#11]

**Comment by MaxTechnics** [comment]
In het regielokaal staan bureaus en accessoires, deze zouden tijdelijk verplaatst moeten worden als ons materiaal er staat

**Comment by MaxTechnics** [comment]
Hiervoor zijn we in communicatie met Facility Kaai

**Comment by RobinCo1** [comment]
> In het regielokaal staan bureaus en accessoires, deze zouden tijdelijk verplaatst moeten worden als ons materiaal er staat

die bureaus kunnen we toch gebruiken om (een deel van) de regie op te zetten?

**Comment by MaxTechnics** [comment]
1 of 2 tafels kunnen we inderdaad wel gebruiken, maar de meeste dingen zoals ladeblokken en dergelijke moeten wel verplaatst worden. Aangezien een groot deel van de regie zelf op poten staat
